"""Deterministic ordinary-language intake boundary for MIRA Studio.

A host/model may interpret customer prose into the structured semantic evidence
accepted here. This module does not invoke a model, create Git work, mutate
source/provider state, publish or install anything, infer approval, or activate
behavior. It validates and projects one bounded reviewable intake draft against
the exact canonical FeatureRegistry.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from hashlib import sha256
import json
import unicodedata

from .feature_registry import FeatureRegistry
from .studio_competition import StudioChangeKind


_MAX_REQUEST_CHARS = 8000
_MAX_OUTCOME_CHARS = 2000
_MAX_ITEM_CHARS = 1000
_MAX_ITEMS = 32


class StudioIntakeError(ValueError):
    """Raised when Studio intake evidence is malformed, contradictory, or unsafe."""


class StudioIntakeNextAction(str, Enum):
    CLARIFY_WITH_CUSTOMER = "clarify_with_customer"
    REVIEW_DRAFT = "review_draft"


@dataclass(frozen=True)
class StudioIntakeRequest:
    """Customer-authored intake evidence.

    Only ordinary-language request text and explicit customer constraints are
    accepted. Internal packet/work/change/Git/provider identifiers are not
    structured inputs to this boundary.
    """

    raw_request: str
    explicit_constraints: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        _text(self.raw_request, "raw_request", max_chars=_MAX_REQUEST_CHARS)
        _customer_items(self.explicit_constraints, "explicit_constraints")


@dataclass(frozen=True)
class StudioSemanticInterpretation:
    """Host/model-produced semantic interpretation to validate deterministically."""

    kind: StudioChangeKind
    desired_outcome: str
    feature_ids: tuple[str, ...]
    customer_constraints: tuple[str, ...] = ()
    assumptions: tuple[str, ...] = ()
    unresolved_questions: tuple[str, ...] = ()
    constraint_conflicts: tuple[str, ...] = ()
    authority_claims: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if not isinstance(self.kind, StudioChangeKind):
            raise StudioIntakeError("kind must be a StudioChangeKind")
        _text(self.desired_outcome, "desired_outcome", max_chars=_MAX_OUTCOME_CHARS)
        _internal_items(self.feature_ids, "feature_ids", allow_empty=False)
        _internal_items(
            self.customer_constraints, "customer_constraints", allow_empty=True
        )
        _internal_items(self.assumptions, "assumptions", allow_empty=True)
        _internal_items(
            self.unresolved_questions, "unresolved_questions", allow_empty=True
        )
        _internal_items(
            self.constraint_conflicts, "constraint_conflicts", allow_empty=True
        )
        _internal_items(self.authority_claims, "authority_claims", allow_empty=True)


@dataclass(frozen=True)
class StudioIntakeDraft:
    """Immutable registry-grounded Studio intake projection with zero execution authority."""

    draft_id: str
    registry_sha256: str
    raw_request: str
    kind: StudioChangeKind
    desired_outcome: str
    feature_ids: tuple[str, ...]
    dependency_ids: tuple[str, ...]
    explicit_constraints: tuple[str, ...]
    assumptions: tuple[str, ...]
    unresolved_questions: tuple[str, ...]
    blockers: tuple[str, ...]
    review_ready: bool
    next_action: StudioIntakeNextAction
    implementation_authorized: bool = False
    source_mutation_authorized: bool = False
    publication_authorized: bool = False
    install_authorized: bool = False
    approval_inferred: bool = False
    activation_authorized: bool = False

    def __post_init__(self) -> None:
        if not self.draft_id.startswith("intake-"):
            raise StudioIntakeError("draft_id must be generated by the intake boundary")
        digest = self.draft_id.removeprefix("intake-")
        if len(digest) != 64 or any(ch not in "0123456789abcdef" for ch in digest):
            raise StudioIntakeError("draft_id must contain a SHA-256 digest")
        if len(self.registry_sha256) != 64 or any(
            ch not in "0123456789abcdef" for ch in self.registry_sha256
        ):
            raise StudioIntakeError("registry_sha256 must be a SHA-256 digest")
        _text(self.raw_request, "raw_request", max_chars=_MAX_REQUEST_CHARS)
        if not isinstance(self.kind, StudioChangeKind):
            raise StudioIntakeError("kind must be a StudioChangeKind")
        _text(self.desired_outcome, "desired_outcome", max_chars=_MAX_OUTCOME_CHARS)
        _internal_items(self.feature_ids, "feature_ids", allow_empty=False)
        _internal_items(self.dependency_ids, "dependency_ids", allow_empty=True)
        _internal_items(
            self.explicit_constraints, "explicit_constraints", allow_empty=True
        )
        _internal_items(self.assumptions, "assumptions", allow_empty=True)
        _internal_items(
            self.unresolved_questions, "unresolved_questions", allow_empty=True
        )
        _internal_items(self.blockers, "blockers", allow_empty=True)
        if set(self.feature_ids) & set(self.dependency_ids):
            raise StudioIntakeError(
                "feature_ids and dependency_ids must describe distinct roles"
            )
        expected_ready = not self.unresolved_questions and not self.blockers
        if self.review_ready != expected_ready:
            raise StudioIntakeError(
                "review_ready must exactly reflect unresolved questions/blockers"
            )
        expected_action = (
            StudioIntakeNextAction.REVIEW_DRAFT
            if self.review_ready
            else StudioIntakeNextAction.CLARIFY_WITH_CUSTOMER
        )
        if self.next_action is not expected_action:
            raise StudioIntakeError("next_action must exactly reflect review readiness")
        for field, value in (
            ("implementation_authorized", self.implementation_authorized),
            ("source_mutation_authorized", self.source_mutation_authorized),
            ("publication_authorized", self.publication_authorized),
            ("install_authorized", self.install_authorized),
            ("approval_inferred", self.approval_inferred),
            ("activation_authorized", self.activation_authorized),
        ):
            if value is not False:
                raise StudioIntakeError(
                    f"Studio intake cannot grant {field.replace('_', ' ')}"
                )

    @property
    def projection_sha256(self) -> str:
        return _digest(
            {
                "draft_id": self.draft_id,
                "registry_sha256": self.registry_sha256,
                "raw_request": self.raw_request,
                "kind": self.kind.value,
                "desired_outcome": self.desired_outcome,
                "feature_ids": list(self.feature_ids),
                "dependency_ids": list(self.dependency_ids),
                "explicit_constraints": list(self.explicit_constraints),
                "assumptions": list(self.assumptions),
                "unresolved_questions": list(self.unresolved_questions),
                "blockers": list(self.blockers),
                "review_ready": self.review_ready,
                "next_action": self.next_action.value,
                "implementation_authorized": self.implementation_authorized,
                "source_mutation_authorized": self.source_mutation_authorized,
                "publication_authorized": self.publication_authorized,
                "install_authorized": self.install_authorized,
                "approval_inferred": self.approval_inferred,
                "activation_authorized": self.activation_authorized,
            }
        )


def build_studio_intake(
    request: StudioIntakeRequest,
    interpretation: StudioSemanticInterpretation,
    registry: FeatureRegistry,
) -> StudioIntakeDraft:
    """Validate semantic evidence and build one deterministic, inert intake draft."""

    if not isinstance(request, StudioIntakeRequest):
        raise StudioIntakeError("request must be a StudioIntakeRequest")
    if not isinstance(interpretation, StudioSemanticInterpretation):
        raise StudioIntakeError(
            "interpretation must be a StudioSemanticInterpretation"
        )
    if not isinstance(registry, FeatureRegistry):
        raise StudioIntakeError("registry must be a FeatureRegistry")

    raw_request = _normalize_text(
        request.raw_request, "raw_request", max_chars=_MAX_REQUEST_CHARS
    )
    explicit_constraints = _canonical_customer_items(
        request.explicit_constraints, "explicit_constraints"
    )
    desired_outcome = _normalize_text(
        interpretation.desired_outcome,
        "desired_outcome",
        max_chars=_MAX_OUTCOME_CHARS,
    )
    feature_ids = _internal_items(
        interpretation.feature_ids, "feature_ids", allow_empty=False
    )
    echoed_constraints = _internal_items(
        interpretation.customer_constraints,
        "customer_constraints",
        allow_empty=True,
    )
    assumptions = _internal_items(
        interpretation.assumptions, "assumptions", allow_empty=True
    )
    unresolved_questions = _internal_items(
        interpretation.unresolved_questions,
        "unresolved_questions",
        allow_empty=True,
    )
    constraint_conflicts = _internal_items(
        interpretation.constraint_conflicts,
        "constraint_conflicts",
        allow_empty=True,
    )
    authority_claims = _internal_items(
        interpretation.authority_claims, "authority_claims", allow_empty=True
    )

    if echoed_constraints != explicit_constraints:
        raise StudioIntakeError(
            "semantic interpretation must preserve explicit customer constraints exactly"
        )
    if set(explicit_constraints) & set(assumptions):
        raise StudioIntakeError(
            "assistant/model assumptions must remain distinct from customer constraints"
        )
    if constraint_conflicts:
        raise StudioIntakeError(
            "semantic interpretation conflicts with explicit customer constraints: "
            + "; ".join(constraint_conflicts)
        )
    if authority_claims:
        raise StudioIntakeError(
            "Studio intake cannot accept implementation/approval/execution authority claims"
        )

    feature_map = registry.feature_map()
    unknown = tuple(sorted(set(feature_ids) - set(feature_map)))
    if unknown:
        raise StudioIntakeError("unknown feature scope: " + ", ".join(unknown))
    dependency_ids = _dependency_closure(feature_ids, feature_map)

    blockers = tuple(
        sorted(f"clarification_required:{question}" for question in unresolved_questions)
    )
    review_ready = not blockers
    next_action = (
        StudioIntakeNextAction.REVIEW_DRAFT
        if review_ready
        else StudioIntakeNextAction.CLARIFY_WITH_CUSTOMER
    )

    identity_payload = {
        "schema_version": 1,
        "registry": {
            "path": registry.source_path,
            "sha256": registry.source_sha256,
        },
        "request": {
            "raw_request": raw_request,
            "explicit_constraints": list(explicit_constraints),
        },
        "interpretation": {
            "kind": interpretation.kind.value,
            "desired_outcome": desired_outcome,
            "feature_ids": list(feature_ids),
            "dependency_ids": list(dependency_ids),
            "assumptions": list(assumptions),
            "unresolved_questions": list(unresolved_questions),
        },
    }
    draft_id = "intake-" + _digest(identity_payload)

    return StudioIntakeDraft(
        draft_id=draft_id,
        registry_sha256=registry.source_sha256,
        raw_request=raw_request,
        kind=interpretation.kind,
        desired_outcome=desired_outcome,
        feature_ids=feature_ids,
        dependency_ids=dependency_ids,
        explicit_constraints=explicit_constraints,
        assumptions=assumptions,
        unresolved_questions=unresolved_questions,
        blockers=blockers,
        review_ready=review_ready,
        next_action=next_action,
    )


def _dependency_closure(
    feature_ids: tuple[str, ...],
    feature_map: dict[str, object],
) -> tuple[str, ...]:
    selected = set(feature_ids)
    dependencies: set[str] = set()
    visited: set[str] = set()
    pending = list(feature_ids)
    while pending:
        feature_id = pending.pop()
        if feature_id in visited:
            continue
        visited.add(feature_id)
        record = feature_map[feature_id]
        for dependency_id in record.dependencies:
            if dependency_id not in selected:
                dependencies.add(dependency_id)
            if dependency_id not in visited:
                pending.append(dependency_id)
    return tuple(sorted(dependencies))


def _digest(value: object) -> str:
    payload = json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")
    return sha256(payload).hexdigest()


def _has_control_characters(value: str) -> bool:
    return any(unicodedata.category(character).startswith("C") for character in value)


def _normalize_text(value: object, field: str, *, max_chars: int) -> str:
    if not isinstance(value, str):
        raise StudioIntakeError(f"{field} must be text")
    if _has_control_characters(value):
        raise StudioIntakeError(f"{field} contains control characters")
    normalized = unicodedata.normalize("NFKC", value)
    normalized = " ".join(normalized.split())
    if not normalized:
        raise StudioIntakeError(f"{field} must not be blank")
    if len(normalized) > max_chars:
        raise StudioIntakeError(f"{field} exceeds {max_chars} characters")
    return normalized


def _text(value: object, field: str, *, max_chars: int) -> str:
    return _normalize_text(value, field, max_chars=max_chars)


def _customer_items(values: object, field: str) -> tuple[str, ...]:
    if not isinstance(values, tuple):
        raise StudioIntakeError(f"{field} must be a tuple")
    if len(values) > _MAX_ITEMS:
        raise StudioIntakeError(f"{field} exceeds {_MAX_ITEMS} items")
    return tuple(
        _normalize_text(value, f"{field}[{index}]", max_chars=_MAX_ITEM_CHARS)
        for index, value in enumerate(values)
    )


def _canonical_customer_items(values: object, field: str) -> tuple[str, ...]:
    normalized = _customer_items(values, field)
    return tuple(sorted(set(normalized)))


def _internal_items(
    values: object,
    field: str,
    *,
    allow_empty: bool,
) -> tuple[str, ...]:
    if not isinstance(values, tuple):
        raise StudioIntakeError(f"{field} must be a tuple")
    if not values and not allow_empty:
        raise StudioIntakeError(f"{field} must not be empty")
    if len(values) > _MAX_ITEMS:
        raise StudioIntakeError(f"{field} exceeds {_MAX_ITEMS} items")
    normalized = tuple(
        _normalize_text(value, f"{field}[{index}]", max_chars=_MAX_ITEM_CHARS)
        for index, value in enumerate(values)
    )
    canonical = tuple(sorted(set(normalized)))
    if normalized != canonical:
        raise StudioIntakeError(f"{field} must be normalized, unique, and sorted")
    return canonical
